---
output: 
  html_document:
    includes:
      in_header: resizer.html
runtime: shiny_prerendered
---


```{r setup, include=FALSE}
library(learnr)
library(rio)
library(tidyverse)
knitr::opts_chunk$set(echo = FALSE, exercise.cap = "prediction-band")

health <- import("https://raw.githubusercontent.com/brendanhcullen/psy612/master/labs/lab-3/data/consc_health.csv")
model <- lm(sr_health ~ consc, data = health)
predicted <- predict(model, interval = "prediction")
pred_plot_data <- cbind(health, predicted)
```


```{r lab-3-glm-ex3, exercise=TRUE}
pred_plot_data %>% 
  ggplot(aes(x = ___, y = ___)) +
  geom_point() +
  geom_smooth(method = "lm") +
  ___(aes(ymin = ___, 
          ymax = ___), 
      fill = "blue", alpha = 0.1) + 
  labs(x = "Conscientiousness", y = "Self-rated health") +
  theme_minimal()
```


```{r lab-3-glm-ex3-solution}
pred_plot_data %>% 
  ggplot(aes(x = consc, y = sr_health)) +
  geom_point() +
  geom_smooth(method = "lm") +
  geom_ribbon(aes(ymin = lwr, 
                  ymax = upr), 
              fill = "blue", alpha = 0.1) + 
  labs(x = "Conscientiousness", y = "Self-rated health") +
  theme_minimal()
```


<div data-iframe-height></div>
